add: files for rack app
romatoom/rack-app pull request #1
Opened 2022-10-18 16:31 UTC by romatoom

2022-10-18 16:54 UTC, BubuntuClu requested changes

2022-10-18 16:54 UTC, BubuntuClu commented on app.rb
> +    router = Router.new
зачем нужна инициализация? что она тебе дает?

2022-10-18 16:54 UTC, BubuntuClu commented on router.rb
> +      name: 'time',
если делать такой объект, то стоит сделать его хэшом, а не просто массивом. чтобы поиск нужного "дейсвтвия" находился по ключу, а не перебором всех элементов

2022-10-18 16:54 UTC, BubuntuClu commented on router.rb
> +  def not_found_response
сделай один метод ответа `response` и в него передавай нужные занчения. зачем тебе отдельный метод под `not_found`?

для ответа используй `Rack::Response`

2022-10-18 16:54 UTC, BubuntuClu commented on utils/time_formatter.rb
> +  AVAILABLE_FORMATS = %w(year month day hour minute second).freeze
это `OPTIONS.keys`

2022-10-18 16:54 UTC, BubuntuClu commented on utils/time_formatter.rb
> +    error_fields = fields.find_all {|f| !AVAILABLE_FORMATS.include?(f)}
первый перебор параметром

2022-10-18 16:54 UTC, BubuntuClu commented on utils/time_formatter.rb
> +    fields.map! {|f| time.strftime(OPTIONS[f]) }
второй перебор параметров

зачем это делать два раза? сделай за один обход заполнение нужных данных

2022-10-18 16:54 UTC, BubuntuClu commented on utils/time_formatter.rb
> +    return { error_fields: error_fields } unless error_fields.length.zero?
почему ответ это хэш какой-то? почему бы не разделить логику на методы, чтобы более гибко управлять ходом выполнения работы?

2022-10-18 16:54 UTC, BubuntuClu commented on router.rb
> +    unless error_fields.nil?
`unless` замени на `if`

2022-10-18 16:54 UTC, BubuntuClu commented on router.rb
> +    self.send route[:action], query_values
параметры метода всегда пишем в скобках

2022-10-19 15:17 UTC, VidgarVii requested changes

2022-10-19 15:17 UTC, VidgarVii commented on utils/time_formatter.rb
> +  end
божественный метод (https://ru.wikipedia.org/wiki/%D0%91%D0%BE%D0%B6%D0%B5%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82). Стоит делегировать ряд задач
Например
 self.fields = []
 self.errors = []
стоит вынести в конструктор и объявить как инстанс переменные

2022-10-19 15:17 UTC, VidgarVii commented on app.rb
> +    if request.request_method == 'GET' && request.path == '/time'
проверку path можно делегировать на утилиту Rack::URLMap. Он как раз будет возвращать 404, если путь не верен

```ruby
require_relative 'time_app'
ROUTES = {
  '/time' => TimeApp.new
}


run Rack::URLMap.new(ROUTES)
```
правда останется решить вопрос с методом запроса

2022-10-19 15:17 UTC, VidgarVii commented on app.rb
> +    get_response(req).finish
тут скорей происходит создание ответа, а не получение?

2022-10-19 15:17 UTC, VidgarVii commented on app.rb
> +    generate_response(status: :internal_server_error, body_content: 'Internal Server Error').finish
ошибки сервера надо чинить, а не отлавливать и показывать юзеру

2022-10-19 15:17 UTC, VidgarVii commented on utils/time_formatter.rb
> +  def formating(time, format = 'year,month,day')
нарушение проектирования класса
Судя по коду я могу сделать так
class TimeFormatter.new.success?
Мне кажется это не совсем логично
я бы пока придерживался стандартного подхода для сервисов
```ruby
result = SomeService.new.call
if result.success?
 ...
else
 ...
end
```

2022-10-19 15:17 UTC, VidgarVii commented on app.rb
> +    time_formatted.formating(Time.now, format)
Суть ответа сервера это показать время в заданном формате.
Получается бизнес задача - показать время в заданном формате
Вот эту бы всю логику и следовало вынести отдельно в сервис, А App использовать только как контроллер, который делегирует запрос и работает напрямую с Rack утилитами. 
Сейчас задача получения времени размазана между модулями программы.

2022-10-19 15:17 UTC, VidgarVii commented on app.rb
> +  def generate_response(status:, body_content:, headers: { 'ContentType' => 'text/plain' })
Для настройки ContentType по умолчанию можно воспользоваться настройкой через Rack::ContentType

https://www.rubydoc.info/gems/rack/Rack/ContentType

и этот код будет не нужным

2022-10-21 16:35 UTC, merged